import "./globals.css";
import { Montserrat } from "next/font/google";

const mont = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lei Ocopio",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mont.className}>
        <div className="bg-sky-300" id="navigation">
          <nav>
            <li className="hover:bg-sky-500 hover:text-white hover:duration-200 hover:ease-in-out">
              Home
            </li>
            <li className="hover:bg-sky-500 hover:text-white hover:duration-200 hover:ease-in-out">
              Resume
            </li>
            <li className="hover:bg-sky-500 hover:text-white hover:duration-200 hover:ease-in-out">
              Portfolio
            </li>
            <li className="hover:bg-sky-500 hover:text-white hover:duration-200 hover:ease-in-out">
              About
            </li>
            <li className="hover:bg-sky-500 hover:text-white hover:duration-200 hover:ease-in-out">
              Socials
            </li>
          </nav>
        </div>

        {children}

        <footer>
          <p>&copy; Lei Ocopio </p>
        </footer>
      </body>
    </html>
  );
}
