import "./globals.css";
import { Montserrat } from "next/font/google";

const mont = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lei Ocopio",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mont bg-emerald-50">
        <div className="bg-green-300" id="navigation">
          <nav>
            <li className="hover:bg-green-600 hover:text-white hover:ease-in-out duration-300">
              <a href="./">Home</a>
            </li>

            <li className="hover:bg-green-600 hover:text-white hover:ease-in-out duration-300">
              <a href="./about">About Us</a>
            </li>

            <li className="hover:bg-green-600 hover:text-white hover:ease-in-out duration-300">
              <a href="./certifications">Certifications</a>
            </li>

            <li className="hover:bg-green-600 hover:text-white hover:ease-in-out duration-300">
              <a href="#">Contacts</a>
            </li>
          </nav>
        </div>

        {children}

        <footer>
          <p>&copy; Lei Ocopio </p>
        </footer>
      </body>
    </html>
  );
}
